### ISSUE TITLE
Required field indicator

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#140]
There needs to be better user interaction surrounding a record not submitting due to a required field not being completed. It also appears that newly updated content must be re-entered. I would prefer the new content remain with an error message or at the very least a message appear that new content must be entered. 

The turquoise circle indicating that a field is required is also illogical.

**Comment by asheill** [comment]
I am also concerted this more of a kora2 to kora3 import issue. Why / how can fields be required but no data be present?

**Comment by austintruchan** [comment]
I conceptualized that we would have a tooltip come off the submit button in the comps explaining that required fields were missing or if fields were inputted incorrectly, so that it would be more clear why the submit button was not working. I believe that was skipped for now to get form validation pushed. In the future we will also have slide in notifications that can help explain these sort of things as well.

For the required field indicators, we could go with a more generic red asteric to indicate them?

**Comment by fritosxii** [comment]
User validation/feedback has not been implemented for record based actions yet. That is in progress. 

As for required fields, my guess is that the records were created before anyone ever set the field to required.
