### ISSUE TITLE
Speed on user management page

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#177]
Checkboxes on user management are slow

**Comment by Dev34** [comment]
User::inAProjectGroup(Project $project) consistently has ~80ms runtime when called only 7 times. Hope that helps!

**Comment by fritosxii** [comment]
@Dev34 Helps eliminate one factor! You are welcome to takeover this ticket if you want. Might be a bit before I can get to it

**Comment by Dev34** [comment]
I'm up for the challenge

**Comment by Dev34** [comment]
Replaced iterative call to addCustomProject() with addNewAdminToAllCustomProjects(). The new function only has two query operations and a single batch insert operation, and is all wrapped in a transaction.
Replaced iterative call to addCustomForm with addNewAdminToAllCustomForms(). The new function executes less queries and does a single batch insert operation, and is all wrapped in a transaction.
Replaced iterative call to removeCustomProject() with bulkRemoveCustomProjects(). The new function executes only a single query operation, batch deletes all relevant records, uses the PHP runtime instead of the database itself to fix the sequences of the projects, and has a single batch insert. Batch deletion and subsequent batch insertion is in this case more efficient than an update operation (which cannot be batched without writing raw MySQL, which would break support for other SQL implementations later). 
Replaced iterative call to removeCustomForm() with bulkRemoveCustomForms(). The new function behaves the same as removeCustomProject() but only batch deletes forms from a project that is affected by the deletion operation. 

Runtimes of all those functions, as well as their old counterparts, is logged in the attached word file [KoraProfiling.docx](https://github.com/matrix-msu/Kora3/files/2192973/KoraProfiling.docx). It implies a performance increase by a factor of 5, but I believe this is due to the database being on a separate server than my dev, which greatly increases the cost of a single database operation and is why batching causes such a significant performance improvement. I would be interested to know how this changes the performance in a production environment where the database is local.

Also disabled checkboxes appearing for a user's own card on the User Management page.

On branch user-management-#177

**Comment by austintruchan** [comment]
After initial testing, I can confirm that what you have done is faster. Its not instantaneous, but is fast enough to allow the user to not get confused anymore, wondering whether or not something happened.
