### ISSUE TITLE
Restore unsuccessful 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#191]
https://e.k3/projects/11/forms/9/records/88430
https://e.k3/projects/11/forms/9/records/revisions/88430

I was not able to successfully restore to a previous version on this record

**Comment by fritosxii** [comment]
It says you rolled-back the record 3 times. What information are you specifically trying to roll back?

**Comment by asheill** [comment]
The content that I changed. But there was no change to the content when I clicked restore.

**Comment by fritosxii** [comment]
Was determined that the revision data was being read backwards. Works as intended

**Comment by fritosxii** [comment]
This record no longer exists :(

**Comment by fritosxii** [comment]
Ok, so I think I found the issue. I just recently refactored revisions because there was a bunch of broken things. Including edit revisions being restored in reverse, which is probably why you were getting the opposite desired result. Revisions will be cleaned up in the next big update. However keep in mind, revisions made before the update will still be messed up.
