### ISSUE TITLE
Speed on Project/Form management

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#213]
Adding/removing users and changing permissions are slow on project/form permissions with larger user set and project/form set

**Comment by Dev34** [comment]
Additionally,
Adding to project groups is currently broken but appears to work because of how the front-end handles moving users from the drop-down to the group. Refreshing the page shows that users don't actually get added.
Deleting a user from a project group occasionally deletes all the users from that project group.

Still in-progress

**Comment by Dev34** [comment]
Note for later:  Bug where each time you remove a user, it registers the removeUser function again. Enforcing a cooldown causes user removal to stop working in general..

**Comment by Dev34** [comment]
This is on the project-permissions-#213 branch (pushed to GitHub).

Added a new function to ProjectGroupController called batchAddUsersAsCustom which accepts an array of users. This function adds a project to multiple users' custom lists with 1 query and 1 insertion.  This replaces iterative use of User::AddCustomProject in ProjectGroupController::create, ProjectGroupController::addUsers, and ProjectGroup::makeAdminGroup.

For ProjectGroupController::addUsers:
< Batched iterative ProjectGroup queries into a single query such that there is now 1 query to fetch the ProjectGroups per user instead of a query for every project group for every user.
< Batched 'new user' operations. Instead of making a call to FormGroupController:addUsers for every new user, a single call is now made with every new user in it. Moved code that fetches the same Forms every time to outside of a loop. Batched fetching FormGroups for new users so that there is only 1 query for all the new users. Also added an optimization that sends the fetched FormGroup to FormGroupController::addUsers instead of doing an unnecessary query by sending the id and fetching it again.  
< Fixed a bug here where a new FormGroupController was being made for every user when we only need one for every FormGroup.

For FormGroupController::addUsers:
< Batched fetching FormGroups such that 1 query is performed to fetch the FormGroups per user, instead of a query for every form group for every user.
< Batched insertions into 'project_group_id'.

Reduced number of deletions performed by ProjectGroupController::removeUser by deleting multiple entries from 'form_group_user' at once (batching).

Fixed small bug in ProjectGroupController::addUser where a call to FormGroupController::addUser had incorrect arguments.
