### ISSUE TITLE
Black text on notifications after signing up

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#342]
Text should be white, like all other notifications

- [x] On load: 
<img width="1170" alt="screen shot 2018-10-18 at 10 13 53 am" src="https://user-images.githubusercontent.com/5408529/47174229-0992fa00-d2de-11e8-9257-8aa33c83f48e.png">

- [x] Another Email has been sent <img width="1076" alt="screen shot 2018-10-18 at 10 14 22 am" src="https://user-images.githubusercontent.com/5408529/47174207-f7b15700-d2dd-11e8-9024-3caf9d3813ba.png">

**Comment by suuuth** [comment]
branch suth-342

**Comment by austintruchan** [comment]
<img width="755" alt="screen shot 2018-10-23 at 10 44 23 am" src="https://user-images.githubusercontent.com/5408529/47368950-a07dfe80-d6b0-11e8-9609-d3c65d778164.png">

- [ ] Looks like the notifications are coming in too far left

- [ ] if possible, add the loading icon when the user selects request another email

**Comment by suuuth** [comment]
Can't seem to recreate this, the notification appears as it should for me.  Maybe try running `compass compile` and re-testing this?  Do you happen to remember what you made the notification appear?

**Comment by austintruchan** [comment]
hmmm, tried running compass compile, but still is too far left for me. This seems to just be the notifications after a succesful signup and landing on the "Thanks for Signing Up" page, and when I hit the Request Another Email button. This is on Chrome.

I think I know the reason. Something in this branch is causing the sidebar to be open / reopen on every page load. The space to the right of the notification is accounting for the sidemenu being open.

**Comment by austintruchan** [comment]
... Well, seems to just be the case when creating a new user. I think possibly because I'm creating the same user with the same username and email each time. I'll continue to test.

**Comment by austintruchan** [comment]
Tried with a different username / email. Sidemenu seems to be open and reopen on every page load still.

**Comment by suuuth** [comment]
I am still unable to reproduce this.  I found some code in `global.js` related to the `keep_sidemenu_open` preference and removed it since that preference no longer exists.  This may or may not fix the issue. 
 Along with this, I added an additional check before the note is displayed to see if both the side menu is open and if the note has the `with-aside` class.  If the sidemenu is not open, and the note has the `with-aside` class, the `with-aside` class is removed from the note, and then the notification is displayed

This should make the notification more consistently display as it should despite whatever is causing the issue
