### ISSUE TITLE
When deleting a record or records on the 'form records & search page', keep the user on that page, instead of returning them to the main form page.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#376]
When deleting a record or records on the 'form records & search page', keep the user on that page, instead of returning them to the main form page.

**Comment by Dev34** [comment]
Deleting a single record and multiple records now both redirect to the 'form records & search' page.

This is on the form-record-nav-#376 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
This seems to work, however, if I use the record multi-select tool to delete records, the toolbar remains after deletion and indicates that the records that were deleted are still selected. The bottom toolbar should close, and not have any records selected after deleting records. Might need help from @suuuth to get this to work since he set it all up.

**Comment by Dev34** [comment]
I noticed this too when I started working on the issue. The selections now get cleared on multi-delete, which solves the issue you described. Selections are now also cleared on single delete because they would stick around in the selections if the record was single-deleted while it was selected/checked.

This is on the form-record-nav-#376 branch

**Comment by austintruchan** [comment]
Nice. Seems to be working well.
