### ISSUE TITLE
New & Edit Field - File Fields - Update placeholder of Max File size and Max File Amount

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#377]
For the file fields on new and edit field pages, make sure the placeholder is displayed on the "Max File Size" and "Max File Amount" inputs. Right now, they display 0 on load. You can see the placeholder is there if you delete the 0, but the placeholder doesn't appear on page load. I'm not sure if there is a reason why this is, but it is confusing having the 0 there on load.

**Comment by Dev34** [comment]
Changed the default creation settings for File Fields such that Max File Size & Max File Amount are now empty strings instead of 0. The existing File Fields in your dev will retain the 0 values because those are saved in the database, but this change will work for any subsequent File Fields you create after pulling this change.

This is on the file-field-inputs-#377 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Ok! Seems to work!
