### ISSUE TITLE
Notify user their session has expired when using two tabs

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#383]
Currently if you open two tabs of Kora3 and are signed into the same account on both, then sign out on one tab, the other tab errors out if you try to do anything because \Auth::user() becomes null. The user then can't reach Kora3 anymore from this tab.

**Comment by fritosxii** [comment]
This is typical of most web applications as they rely on Session to authenticate. Since the session is stored to the URL, if you logout on one tab, it logs out of all tabs because all tabs point to the same Session.

@Dev34 The next question is, does it break with an error, or does it just redirect to login?

**Comment by fritosxii** [comment]
Can you tell me a specific button/link that triggers the error?

**Comment by Dev34** [comment]
I took a look at the stack trace that was causing this error in the blade file and found it was caused by some code I added that hasn't been committed yet, specifically a fallback route I added to serve 404 pages with the user's session data. I'll fix this in my branch before I make a pull request for that issue. Tested on master and this bug doesn't occur.
