### ISSUE TITLE
Dashboard performance

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#433]
issues with customized dashboard performance:

- Dashboard page loads, but blocks take a long time to load.  I have a demo project, Twitter, Quote, and note tiles on my dashboard, and it took 15-20 seconds for them to appear.

- This same issue exists when you are adding a new tile.  Takes a long time (for me, 15-20 seconds) to refresh with the new tile.  

Does the "Edit your Dashboard" feature do anything?  Because it doesn't work for me at all.  Tiles can't be dragged, new sections can't be added or renamed, etc.  

On on a mac (10.14), Chrome  71.0.3578.80

**Comment by watrall** [comment]
also, when waiting for the tiles to load, the menu sidebar either won't open or close.

**Comment by austintruchan** [comment]
Yes the edit dashboard should be working. Are you testing on kora3.matrix.msu.edu? If so, this could be why, that installation is not up to date as far as I know.

**Comment by fritosxii** [comment]
@watrall Quilts is the only installation that is up to date. What are you testing on?

**Comment by fritosxii** [comment]
I have confirmed that dashboard loads very slowly on my installation. This will need to be looked into.

**Comment by Dev34** [comment]
I'm unable to reproduce the performance issues mentioned. I added a moderately sized project, Quote blocks, Twitter block, and Note blocks. @fritosxii Could you confirm again that there are performance issues with the dashboard on your install?

**Comment by watrall** [comment]
are you testing on your own K3 install or the main kora3.matrix.msu.edu install?  The performance issue expressed itself on on the kora3.matrix install, not smaller installs.

**Comment by Dev34** [comment]
I'm testing on my own instal. I'll go try it out on the live site.

**Comment by watrall** [comment]
obviously has something to do with the size of the install.

**Comment by Dev34** [comment]
I created another test case on the live site install. Getting the same page load time of ~4-5 seconds for empty dashboard and with the test case, which implies the page load time is largely independent of the dashboard retrieval code. Please comment if anyone can reproduce!

**Comment by fritosxii** [comment]
Multiple people have commented that they have issues on kora3. I had similar issues on my dev with only one large project. Just scan the DB calls and see if anything stands out as odd. My guess is the population of record IDs in the add Record Block.

**Comment by Dev34** [comment]
I profiled the execution times of the relevant DB calls, and they don't impact performance much at all. As Anthony predicted, the performance bottleneck is that an <option HTML element is generated for every Record that the user can add as a block. A similar issue would occur with Forms and Projects if there were a very high number of those that could be added as blocks. With ~100,000 Records in a select box, issues start to occur, likely related to how the browser sets up the DOM. Even with 100,000 Records tested, the filesize of the markup file generated is only 12MB - so filesize isn't the bottleneck. A potential solution would be to have users search for the Record they want to add as a block using some parameter such as name or record id. This avoids sending way too much data to the user.

Tabling this issue due to the rebuilding of back-end systems.

**Comment by fritosxii** [comment]
Rebuilt how we add record blocks, so large installations will no longer affect the dashboard since we do not load all Record IDs anymore in the new system
