### ISSUE TITLE
Form Associatons page bugs

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#436]
Two bugs:

- [ ] When you add a permission, we need to refresh the page so the User sees the newly added permission

- [ ] Fix the trash icon position on that new permission card

<img width="978" alt="screen shot 2018-12-11 at 2 19 24 pm" src="https://user-images.githubusercontent.com/4040076/49824458-208b2100-fd50-11e8-9dd8-8df3b33956d1.png">

**Comment by Dev34** [comment]
Trash icon now appears correctly & fixed transitioning from empty-state to non-empty-state with a refresh.

This is on the form-associations-bugs-#436 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
- [ ] Fix the add association permissions modal so that it doesn't scroll when the form input is open. Also update it so the dropdown drawer for the form input opens up and falls over the bottom edge of the modal. Should work and behave the same way as the Request project permissions modal.

- [ ] Within this modal, Selecting a form and then hitting Create New form association doesn't seem to do anything. Modal remains open and I am not sure if it worked or not.

- [ ] Update form list within the modal to be alphabetical by project title, then form title.

- [ ] Positioning of trash icon is good, however tooltip for trash icon needs to be positioned better. 
<img width="356" alt="screen shot 2019-01-23 at 10 33 10 am" src="https://user-images.githubusercontent.com/5408529/51617717-cc509080-1efa-11e9-8acd-73db1d542908.png">

**Comment by Dev34** [comment]
Fixed up the 'Create a New Form Association' modal - removed scrollbar, dropdown now falls over the modal, and the contents are now sorted alphabetically.
Trash icon placement is now closer to the trash container - did you want it centered with the trash container as well?

This is on the form-associations-bugs-#436 branch (pushed to GitHub)

**Comment by Dev34** [comment]
Tooltip is now centered above trash icon for both "Request Form Association" and "Create Form Association" modals. The other tooltip and trash container spacing fixes were also added to the "Request Form Association" modal.

"Request Form Association" modal is now also alphabetically sorted, has a notification on submit, the modal dropdown now falls over the modal, and there's no scrollbar anymore.

Please run ```compass compile```
This is on the form-associations-bugs-#436 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Ok I think all is good.

Last thing, if its possible, keep the user on the request form association tab after requesting a form association.

**Comment by Dev34** [comment]
User now arrives at Request Form Association tab after requesting a form association.

Please run `compass compile`
This is on the form-associations-bugs-#436 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Works!
