### ISSUE TITLE
Generated List record input

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#438]
Generated List input needs to behave like the custom list order input in the options pages for Multi-Select List and Generated List.

**Comment by suuuth** [comment]
branch `suth-438`

**Comment by suuuth** [comment]
Changes made to the `record-create` and `record-edit` page

Before:
![before](https://user-images.githubusercontent.com/31667253/52878543-e14fc680-312a-11e9-932a-157d22202561.PNG)
After:
![after](https://user-images.githubusercontent.com/31667253/52878549-e6147a80-312a-11e9-9de7-ed09338fb87b.PNG)

URLs for testing/reviewing:
`/Kora3/public/projects/193/forms/410/records/create`
`/Kora3/public/projects/193/forms/410/records/9420/edit`

**Comment by austintruchan** [comment]
If i'm not mistaken, you're going to want to remove that entire top input, so you just have the 'add list options below, and order them....' input section.

**Comment by suuuth** [comment]
So every item that appears in a card in the 'add list options below` section is selected for this field?  Or should there be some distinction between a selected item and one that isn't selected?

**Comment by austintruchan** [comment]
Hold on, Okay. I misread anthony's awful description. Let me think about this. I think there potentially could be a better way to approach this. A better solution may come in a future ticket ...

But what you did before works, and could be a solution in the mean time. I would maybe alter the 'add list options below` section so that the options aren't reorderable, or deletable. 

And if possible, if an option is added, it is auto added to the select list above.

**Comment by suuuth** [comment]
- [ ] alter the 'add list options below` section so that the options aren't reorderable
  - [ ] or deletable
- [ ] make the options you add deletable

**Comment by suuuth** [comment]
All set for review

**Comment by austintruchan** [comment]
This looks good!

**Comment by austintruchan** [comment]
@fritosxii Wait... Why does "Generated List input needs to behave like the custom list order input in the options pages for Multi-Select List and Generated List." ?

Nick is working on this now, but I don't recall why we need that second section at all?
