### ISSUE TITLE
Gallery Fullscreen Modal Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#439]
<img width="1715" alt="screen shot 2018-12-13 at 2 12 05 pm" src="https://user-images.githubusercontent.com/5408529/49961675-43990a80-fee1-11e8-8299-e8338c951aeb.png">

- [x] At the moment it seems like no matter what the gallery fullscreen modal has a max height of ~400px. If possible, this height should be limited, but grow dependent upon the browser height, growing the image proportionately.

**Comment by suuuth** [comment]
- images were placed inside an absolutely positioned div, which prevented child images from expanding past the set height for the absolute parent (which was `min-height: 400px`).  Image parent containers for the currently selected image now have `position: static`, which fixes this issue
- images were being loaded and displayed with smaller dimensions than they were uploaded with.  This has been corrected.  Images now display with their original dimensions in the fullscreen modal
- adjusted scss to account for these changes

This can best be seen here: `/public/projects/199/forms/248/records/9366`

All set for first review

**Comment by austintruchan** [comment]
Looks good!

**Comment by austintruchan** [comment]
Wow. I definitely commented on the wrong issue. This does not look good. lol.

**Comment by austintruchan** [comment]
For the fullscreen preview modal, it looks like just the image has been increased in size. What I really want is the container that is the modal, to adjust to the height of the image, instead of remaining at whatever the max height is set at. 

Right now I see: 
<img width="871" alt="screen shot 2019-01-23 at 10 10 58 am" src="https://user-images.githubusercontent.com/5408529/51616300-c73e1200-1ef7-11e9-9bae-77658a4dac1b.png">
followed by this when clicking on the image: 
<img width="1433" alt="screen shot 2019-01-23 at 10 10 28 am" src="https://user-images.githubusercontent.com/5408529/51616324-d02ee380-1ef7-11e9-975d-8f1717e4cbaa.png">

The image's dimensions should be contained within the modal boundaries, but the height of the modal should adjust to allow the image to be as big as possible while remaining inside the height of the browser.

**Comment by suuuth** [comment]
I had applied a fix to the record-show page, which fixed this issue on that page, but caused issues on the record-index page that you were seeing.  The fix has been applied now to both pages and this looks like its ready for another review.

**Comment by austintruchan** [comment]
For the full screen modal, I am still seeing the image is still being blown out of proportion. Should keep the same proportions, and the entire image should be viewable. The modal height is taller now, which is good, but the image should be contained within still: 
<img width="1649" alt="screen shot 2019-01-25 at 11 36 38 am" src="https://user-images.githubusercontent.com/5408529/51759234-c0e59c80-2095-11e9-880e-9c3c3f460d02.png">

**Comment by suuuth** [comment]
I had `max-height: 100%` applied to the images, but as it turns out this [doesn't limit the height of the image if the parent container doesn't have an explicitly defined height.](https://www.w3.org/TR/CSS2/visudet.html#min-max-heights) 

Added a bit of jquery to address this.  Explicit height values are now applied dynamically and this should consistently keep the entire image within the bounds of the modal.  All set for review.

**Comment by austintruchan** [comment]
Ok. I think this is good. But could you send me a link to a record that has multiple images in the gallery field? The link you provided earlier has a gallery field with all blank images.

**Comment by suuuth** [comment]
You may need to upload photos manually to see a record with multiple photos if you can't see them in [this record](http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/forms/248/records/9366).  For me, I can't see any photos that anyone else has uploaded, which is why I created a new record and uploaded photos to it.  You may need to do the same.

**Comment by austintruchan** [comment]
Okay I did so. I think we're good.
Can you test the speed of the images loading in the gallery? Idk if the network is slow or what, but the gallery images seems to load very slowly for me.

public/projects/199/forms/402/records/9374

**Comment by suuuth** [comment]
Yes I will see what I can do.

**Comment by suuuth** [comment]
According to Chrome's DevTools' Network panel:  requesting, responding and downloading/displaying images consistently takes from 500ms to 1000ms, regardless of the size of the image.  This was tested with images ranging in size from 10.1kb to 1.3mb.  About **80%** of this time is spent on just waiting for a response from the server (time to first byte).

I believe this indicates a performance issue rather than a slow-network issue?  According to [this](https://www.searchenginepeople.com/blog/16081-time-to-first-byte-seo.html), this time (time to first byte) averages between 100-500ms.  From these tests, we're getting about 500-700ms.

Tested on these pages:
[http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/forms/407/records/9378](http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/forms/407/records/9378)
[http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/forms/407/records/9379](http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/forms/407/records/9379)

Screenshots:
![9378-record](https://user-images.githubusercontent.com/31667253/52150106-f1e94280-263c-11e9-92a3-c5ab942e63c7.PNG)
![9379-record](https://user-images.githubusercontent.com/31667253/52150121-fca3d780-263c-11e9-9011-af22cd760144.PNG)
The colored bar on the far right column is total time it took to request/get/download the asset, and the green section is the time spent waiting on a response from the server.  The column immediately to the left shows total time in ms, and to the left of that is the filesize.  **This is for images that load and display properly for me.**  On the record you linked, the images don't display for me ( `500 internal server error` ), and yet these broken images also spend between 350ms and 450ms just waiting on a response from the server.

Does this help?  @austintruchan

**Comment by austintruchan** [comment]
Wow. Yes it does help. I've retested the speeds and they are much faster than I tested before, so we're good to go. Just wanted to make sure it wasn't a network issue.
