### ISSUE TITLE
Invite users to a project from project permissions page.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#48]
https://projects.invisionapp.com/d/main#/console/11107725/236966805/preview

**Comment by austintruchan** [comment]
These new modals look good.

So will the usernames update to their full name after the come in and make an account?

- [ ] I tried inviting myself with a new email, but haven't recieved an email. Have you done anything with emailing yet?

**Comment by Dev34** [comment]
Yes, once the invited users confirm their accounts and set their first and last names, then their full names will appear in the name rectangles instead of their usernames (username is the part before the @ in the email). If by chance they only have a first or last name defined, then it'll pick whichever one is defined.

The email features of Kora3 have been broken for a long time on my dev, so nothing sends. Not sure what's going on with this so I'll ask Anthony. Currently, it's sending a default invite email like the one you'd get from inviting a user from the User Management page. It should work on the live site.

**Comment by austintruchan** [comment]
Gotchyaaaa. Okay sounds good.

**Comment by Dev34** [comment]
@austintruchan According to Anthony, emailing has not worked for some time on our devs, but does work on the live site. Is there anything else I need to do with this task?

**Comment by austintruchan** [comment]
I believe thats it!
