### ISSUE TITLE
Gallery Field File Input Erroring

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#518]
Often times when uploading an image to the gallery file on a create record page, I am greeted with a static green loading bar: 
<img width="968" alt="screen shot 2019-03-05 at 11 52 58 am" src="https://user-images.githubusercontent.com/5408529/53822245-5ac62200-3f3d-11e9-9e8c-edf8caccea5d.png">

I understand that this usually fills out to 100% and then shows the uploaded image card. However sometimes it just sits there, and me as the user have no idea why. Even me, as the designer have no idea why. 

After some testing there is a max file size that I assume is standard across all image uploads. The image I was trying to upload was 3mb in size, but was unable to upload. All other images less than that were able to upload.

More interestingly, the error message the field provided is "invalid file type provided", even though its the same file type I have been successfully uploading to the same field 5 seconds beforehand.

We need to either allow larger filesizes to be uploaded, or provide proper error messaging.

Instead of a static 100% loaded green loading bar, if possible if we could replace that with orange text that says, "Filesize is too large to upload" that would be better.

**Comment by Dev34** [comment]
> After some testing there is a max file size that I assume is standard across all image uploads. The image I was trying to upload was 3mb in size, but was unable to upload. All other images less than that were able to upload.

What you were experiencing is the PHP max_upload_size configuration variable, which typically defaults to 2MB. This setting is independent of the Kora3 installation, so there's a special orange text error message that comes up telling the user to 'contact the system administrator' if they upload an image that surpasses this setting.
A bug with type-checking was causing this error message not to show up, and that bug is now fixed; All the error messages should now be working correct.

Also, the progress bar should now disappear properly after a successful or failed image upload.
A side-note on the progress bar is that Matrix's gigabit upload speed makes it so that the progress bar doesn't show any progress - instead it goes from 0% to 100% immediately because it uploads it in one chunk. I realized this when I saw that the bitrate of the upload was equal to the filesize for images I tested.

This is on the gallery-erroring-#518 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Ok. Would we have the option to increase the 2mb maximum? And would have the ability to change that error message, or switch it out for our own error message?

**Comment by Dev34** [comment]
@austintruchan Yes, the 2MB maximum can be changed. It's up to the system administrator for a given installation to go into their PHP settings and set that config value because it can't be synced with Git. Then it will automatically use that config value in Kora3.

Yes, we can change the error message to be anything you want! Here's [a link to the current error messages](https://github.com/matrix-msu/Kora3/blob/a6ea9078ede970093865bc6549429b5af5eb117b/app/FieldHelpers/UploadHelper.php#L23) for file uploads. More info on the ones that start with numbers (lines 23-29) can be found [here](http://php.net/manual/en/features.file-upload.errors.php). A few of the error messages aren't used, I think.

**Comment by austintruchan** [comment]
Gotcha. Now I understand.

And okay. For the error messages, I think for now if we could use the more friendly versions that are in the code to the link you provided (lines 31-40), instead of the "CONTACT SYSTEM ADMINISTRATOR" error messages that would be good. Let me know if you what is there doesn't quite work of if you need specific wording for a certain error message.
