### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#53]
Update 404 page to look like: https://projects.invisionapp.com/d/main#/console/11107725/327251251/preview

**Comment by austintruchan** [comment]
.... Anthony, whats wrong?

**Comment by Dev34** [comment]
resources/views/errors/404.blade.php

**Comment by austintruchan** [comment]
If possible, I would also have you update the "Whoops something went wrong" page with this design as well. Just don't need the 404 text, and can update the text to read "Whoops something went wrong" instead of "we couldn't find the page ...". For this 'whoops something wen wrong page', keep the contact kora installation admin text and then maybe have the "Go to Kora Home" be "Go Back" and have it take the user back to the previous page they were on.

**Comment by austintruchan** [comment]
- [ ] Update "Feel free to contact the Installation Admin" and "about this problem, or ..." to be ubuntu-regular

**Comment by Dev34** [comment]
Updated the font for those two text blocks to regular ubuntu.

This is on the 404-#53 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Good, but you'll want to keep the email link to remain ubuntu medium.

**Comment by Dev34** [comment]
Updated the font for the email link to be ubuntu medium.

Please run ```compass compile```
This is on the 404-#53 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Okay this looks good.
