### ISSUE TITLE
Placeholder Values Missing on Several Pages

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#91]
On many new field pages, and probably some single field pages, there exists inputs that contain no placeholders. Eg, regex fields. All field inputs should have placeholder text.

**Comment by Dev34** [comment]
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/7/forms/17

**Added placeholders and swapped default values with placeholder text for New Field pages**
- Added placeholder to New Field (Rich Text) _Default_ field
- Added placeholders to New Field (Number) _Minimum Value_, _Maximum Value_, _Unit of Measurement_ ... and changed _Value Increment_ field from default value of "1" to placeholder text of "Enter value increment here"
- Added placeholder to New Field (Generated List) _Regex_ field
- For New Field (Date), replaced _Start Year_ field default value of "1900" with placeholder text of "Enter start year here" and replaced _End Year_ field default value of "2020" with placeholder text of "Enter end year here"
- ^ Same as above for New Field (Schedule)
- For New Field (Documents), replaced _Max File Size (kb)_ field default value of "0" with placeholder text of  "Enter max file size (kb) here" and replaced _Max File Amount_ default value of "0" with placeholder text of "Enter max file amount here"
- Replaced all fields' default values with placeholder texts for New Field (Gallery), New Field (Playlist), New Field (Video), and New Field (3D Model)

**For the Single Field pages, if the user does not set a value for a field or the user deletes their existing value, then the corresponding placeholder text is now shown. (Otherwise the value of the field is shown)**

**Comment by austintruchan** [comment]
- [ ] For minimum and max file labels and placeholders, lets make them consistent, so they both say minimum and maximum, instead of min and max. 

Otherwise this all looks good.

**Comment by Dev34** [comment]
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/7/forms/17

Changed 'max' labels and placeholders to 'maximum' and 'min' to 'minimum'

This is on the placeholder-fix-#91 branch

**Comment by austintruchan** [comment]
This looks good for all the new field input values.

We should also expand this to the placeholder values when creating a new record, for fields that don't have a default value set. The only one that I specifically noticed, was the text field that needed a placeholder added, but would be good to double check all of them.

**Comment by Dev34** [comment]
http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/8/forms/16/records/create
branch: placeholder-fix-#91 (pushed to GitHub)

Text & Rich Text didn't have placeholders. Added placeholder to Text input, but couldn't figure out how to add a placeholder to the Rich Text input.

**Comment by austintruchan** [comment]
I think this is good! But i noticed that multilined text fields don't get a placeholder. Is this possible to get the same placeholder as single lined text fields for multilined text fields?

**Comment by Dev34** [comment]
Hmm, you're not referring to the Rich Text fields, are you? I can't figure out how to apply placeholders for those.

I think I know what you mean by the multilined text fields (e.g Description field for New Field), but I wasn't able to find any multilined text fields in New Field or New Record that don't have placeholders. Any idea where I can find them?
@austintruchan

**Comment by austintruchan** [comment]
Yep, you just have to set any text field to be multi-lined. You can do that in the text fields advanced options.

**Comment by Dev34** [comment]
When I set the Text Field to be multi-lined, none of the placeholders disappear, and the placeholders also appear in that field's options after creation. Any idea where I can find these inputs that are missing placeholders?

**Comment by austintruchan** [comment]
Looks like when you create a field that is multilined, and does not have a default text and then go to the create new record, that field appears to not have a placeholder.

**Comment by austintruchan** [comment]
I see that there is now a placeholder for multi-lined text fields on the create new record page. Assuming everything else still works. I think we are good to go!
